--------------------------------------------------------
--  DDL for Table HEALTH_PRO_DATA
--------------------------------------------------------


  CREATE TABLE "CONSTRACK"."HEALTH_PRO_DATA" 
   (	"PMI_ID" VARCHAR2(26 BYTE), 
	"BIOBANK_ID" VARCHAR2(26 BYTE), 
	"LAST_NAME" VARCHAR2(26 BYTE), 
	"FIRST_NAME" VARCHAR2(26 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"LANGUAGE" VARCHAR2(26 BYTE), 
	"PARTICIPANT_STATUS" VARCHAR2(26 BYTE), 
	"GENERAL_CONSENT_STATUS" NUMBER(3,0), 
	"GENERAL_CONSENT_DATE" DATE, 
	"EHR_CONSENT_STATUS" NUMBER(3,0), 
	"EHR_CONSENT_DATE" DATE, 
	"WITHDRAWAL_STATUS" NUMBER(3,0), 
	"WITHDRAWAL_DATE" DATE, 
	"STREET_ADDRESS" VARCHAR2(128 BYTE), 
	"CITY" VARCHAR2(80 BYTE), 
	"STATE" VARCHAR2(26 BYTE), 
	"ZIP" VARCHAR2(80 BYTE), 
	"EMAIL" VARCHAR2(128 BYTE), 
	"SEX" VARCHAR2(26 BYTE), 
	"GENDER_IDENTITY" VARCHAR2(26 BYTE), 
	"RACE_ETHNICITY" VARCHAR2(128 BYTE), 
	"EDUCATION" VARCHAR2(128 BYTE), 
	"PHONE" VARCHAR2(20 BYTE)
   ) ;
