--------------------------------------------------------
--  DDL for View HEALTH_PRO_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "HEALTH_PRO_VIEW" ("HP_PMI_ID", "HP_LAST_NAME", "HP_FIRST_NAME", "HP_DATE_OF_BIRTH", "HP_GENERAL_CONSENT_STATUS", "HP_GENERAL_CONSENT_DATE", "HP_EHR_CONSENT_STATUS", "HP_EHR_CONSENT_DATE", "HP_WITHDRAWAL_STATUS", "HP_WITHDRAWAL_DATE", "PMI_ID", "MRN", "MRN_FACILITY", "LAST_NAME", "DATE_OF_BIRTH", "CONSENT_DATE", "CURRENT_STATUS", "VALIDATED_ID") AS 
SELECT 
   "HP_PMI_ID","HP_LAST_NAME","HP_FIRST_NAME","HP_DATE_OF_BIRTH","HP_GENERAL_CONSENT_STATUS","HP_GENERAL_CONSENT_DATE","HP_EHR_CONSENT_STATUS","HP_EHR_CONSENT_DATE","HP_WITHDRAWAL_STATUS","HP_WITHDRAWAL_DATE","PMI_ID","MRN","MRN_FACILITY","LASTNAME", "DOB", "CONSENT_DATE","CURRENT_STATUS", "VALIDATED_ID" 
FROM 
  (SELECT PMI_ID AS HP_PMI_ID, LAST_NAME AS HP_LAST_NAME, FIRST_NAME AS HP_FIRST_NAME, DATE_OF_BIRTH AS HP_DATE_OF_BIRTH, GENERAL_CONSENT_STATUS AS HP_GENERAL_CONSENT_STATUS, GENERAL_CONSENT_DATE AS HP_GENERAL_CONSENT_DATE, EHR_CONSENT_STATUS AS HP_EHR_CONSENT_STATUS, EHR_CONSENT_DATE AS HP_EHR_CONSENT_DATE, WITHDRAWAL_STATUS AS HP_WITHDRAWAL_STATUS, WITHDRAWAL_DATE AS HP_WITHDRAWAL_DATE FROM HEALTH_PRO_DATA) HPD
FULL OUTER JOIN 
 (SELECT SID.STUDY_ID AS PMI_ID,  M.MRN, MF.NAME AS MRN_FACILITY, P.LASTNAME, P.DOB, PC.CONSENT_DATE, C.TEXT AS CURRENT_STATUS, VALIDATED.TEXT AS VALIDATED_ID FROM PATIENT_CONSENT PC 
JOIN CONSENT_FORM CF ON PC.CONSENT_FORM_FK = CF.ID
JOIN IRB_PROTOCOL IRB ON CF.IRB_PROTOCOL_FK = IRB.ID AND IRB.PROTOCOL_NUMBER = '2017P000508'
JOIN MRN M ON PC.MRN_FK = M.ID
JOIN MRN_FACILITY MF ON M.MRN_FACILITY_FK = MF.ID
JOIN PATIENT P ON P.ID = M.PATIENT_FK
JOIN (SELECT STUDY_ID.PATIENT_FK, STUDY_ID.STUDY_ID FROM STUDY_ID JOIN IRB_PROTOCOL IRB ON STUDY_ID.IRB_PROTOCOL_FK = IRB.ID AND IRB.PROTOCOL_NUMBER = '2017P000508') SID ON SID.PATIENT_FK =  P.ID
JOIN PT_CONSENT_STATUS PCS ON PC.ID = PCS.PATIENT_CONSENT_FK
JOIN CONSENT_STATUS_SINGLE CSS ON PCS.ID = CSS.ID
JOIN QUESTION Q ON PCS.QUESTION_FK = Q.ID
JOIN QUESTION_TYPE QT ON QT.ID = Q.QUESTION_TYPE_FK AND QT.TYPE  = 'Consent'
JOIN CHOICE C ON CSS.CHOICE_FK = C.ID AND C.TEXT IN ('Consented')
JOIN (SELECT PCS.PATIENT_CONSENT_FK, C.TEXT FROM PT_CONSENT_STATUS PCS
      JOIN CONSENT_STATUS_SINGLE CSS ON PCS.ID = CSS.ID
      JOIN QUESTION Q ON PCS.QUESTION_FK = Q.ID
      JOIN QUESTION_TAG QTAG ON QTAG.QUESTION_FK = Q.ID
      JOIN TAG T ON T.ID = QTAG.TAG_FK AND T.CODE = 'VID'
      JOIN CHOICE C ON C.ID = CSS.CHOICE_FK) VALIDATED ON VALIDATED.PATIENT_CONSENT_FK = PC.ID) PMI_CONSENTED ON PMI_CONSENTED.PMI_ID = HPD.HP_PMI_ID;
