--Create all the PII tables
CREATE TABLE PII_NAME
(PERSON_ID INTEGER NOT NULL,
FIRST_NAME VARCHAR(120),
MIDDLE_NAME VARCHAR(120),
LAST_NAME VARCHAR(120),
SUFFIX VARCHAR(120),
PREFIX VARCHAR(120));

CREATE TABLE PII_EMAIL
(PERSON_ID INTEGER NOT NULL,
EMAIL VARCHAR(120));


CREATE TABLE PII_PHONE_NUMBER
(PERSON_ID INT NOT NULL,
PHONE_NUMBER VARCHAR(120));

CREATE TABLE PII_ADDRESS
(PERSON_ID INTEGER NOT NULL,
LOCATION_ID INTEGER);

CREATE TABLE PII_MRN
(PERSON_ID INTEGER NOT NULL,
HEALTH_SYSTEM VARCHAR(120),
MRN VARCHAR(120));

CREATE SEQUENCE dbo.LOCATION_ID_SEQ START WITH 1 INCREMENT BY 1 CACHE 20;


